header:
  version: 1.1
  supported_extensions: nef, tiff, tif, jpg, jpeg, gif, png, bmp, raw, pcx
file_handling:
  ipad:
    low:
      default:
        storage:
          location: internal
          representation: none
      NEF_TIF:
        filter:
          extensions: NEF, TIF, TIFF
        storage:
          location: internal
          representation: 1024x768
      1024x768:
        filter:
          max_scale: 1024,768
          extensions: all
        storage:
          location: internal
          representation: 1024x768
    high:
      default:
        storage:
          location: internal
          representation: none
      NEF_TIF:
        filter:
          extensions: NEF, TIF, TIFF
        storage:
          location: internal
          representation: RAW2400x2500
  local_computer:
    low:
      default:
        storage:
          location: internal
          representation: none
      1024x768:
        filter:
          max_scale: 1024,768
          extensions: all
        storage:
          location: internal
          representation: 1024x768
    high:
      default:
        storage:
          location: internal
          representation: none
      JPG_PNG:
        filter:
          extensions: JPG, PNG
        storage:
          representation: None
      NEF_TIFF:
        filter:
          max_scale: 2400,1500
          extensions: NEF, TIFF
        storage:
          location: internal
          representation: RAW2400x2500
