header:
  version: 1
meta:
  query_type: StructuredKioskQuery
  category: "Archaeological Entities"
variables:
  op_param: ["dsd('unit', 'arch_context')"]
queries:
  'anc_lots_by_op':
    name: '#: List all lots of an OP'
    description: '#: Lists all lots per OP'
    type: 'SQL'
    output_type: 'list'
    query: "  
select lot.id lot_id, locus.arch_context arch_context from lot
    inner join locus on lot.uid_locus= locus.uid
    inner join unit on locus.uid_unit = unit.uid
where unit.arch_context = {{#op_param}}
order by lot.id
      "
    column_information:
      arch_context: DSD('locus','arch_context')
      lot_id: DSD('lot','id')
