header:
  version: 1
meta:
  query_type: StructuredKioskQuery
variables:
  unit_id: ["dsd('unit', 'arch_context')"]
queries:
  'material_types_of_unit_x_sql':
    name: 'What materials (and how much of each) were found in unit x?'
    description: 'Lists the materials found in a certain unit and shows count and weight by material'
    type: 'SQL'
    output_type: 'list'
    query: "
      select unit.arch_context unit_id,
       cm.type material,
       sum(cm.weight)::float weight,
       sum(cm.quantity)::float quantity
       from {{unit}} unit
         inner join {{locus}} locus on unit.uid = locus.uid_unit
         inner join {{collected_material}} cm on locus.uid = cm.uid_locus
      where unit.arch_context = {{#unit_id}}
      group by unit.arch_context, cm.type
      order by sum(cm.weight) desc,sum(cm.quantity) desc, cm.type"
    charts:
      chart1:
        type: "pie"
        title: "#: % material in #(/$/constants/labels/unit) #(/variables/inputs/unit_id) by quantity"
        categories: "material"
        values: "quantity"
      chart2:
        type: "pie"
        title: "#: % material in #(/$/constants/labels/unit) #(/variables/inputs/unit_id) by weight"
        categories: "material"
        values: "weight"
      chart3:
        type: "bar"
        title: "#: materials and their quantities in #(/$/constants/labels/unit) #(/variables/inputs/unit_id)"
        categories: "material"
        values: "quantity"
      chart4:
        type: "bar"
        title: "#: materials and their weights in #(/$/constants/labels/unit) #(/variables/inputs/unit_id)"
        categories: "material"
        values: "weight"
    column_information:
      unit_id: DSD('unit','arch_context')
      material: DSD('collected_material','type')
      weight: DSD('collected_material','weight')
      quantity: DSD('collected_material','quantity')


