header:
  version: 1
meta:
  query_type: StructuredKioskQuery
variables:
  involved: ["dsd(excavator, id)", "label(participant)", "input_default(null)"]
queries:
  'todos':
    name: 'tasks on the to-do list'
    description: 'Shows all tasks that are currently on the to-do list'
    type: 'SQL'
    output_type: 'list'
    query: "
      select todos.title \"to-do\",
       todos.involved participants,
       todos.priority priority,
       todos.until \"date\",
       todos.state state 
       from {{todos}} todos
       where coalesce({{#involved}},'')='' or todos.involved ilike {{#involved}}
      order by state, until, priority, title
    "
