import_configurations:
  - kiosk_default_config.yml
  - kiosk_local_config.yml
  - kiosk_secure.yml
  - '%custom_path%\anc_kiosk_config.yml'
#  - '%custom_path%\custom_config\kiosk_u2ers.yml'


config:
  # The project_id must be in the kiosk_config file! Some tools rely on that convention!
  #  project_id: 'u2ers'
  base_path: 'C:\notebook_source\kiosk\server\kiosk\kiosk'
#  project_id: "anc"
  project_id: "anc"
