import_configurations:
  - kiosk_default_config.yml
  - kiosk_local_config.yml
  - kiosk_secure.yml
#  - '%custom_path%\project_id_kiosk_config.yml'


config:
  # The project_id and the base_path must be in the kiosk_config file! Some tools rely on that convention!
  project_id: ''  # the Kiosk project ID. It must be unique and must never change!
  base_path: ''  # the root directory for Kiosk on this machine