import_configurations:
  - kiosk_default_config.yml
  - kiosk_local_config.yml
  - kiosk_secure.yml

config:
  autoload_plugins_buap:
    - 'buap_ancdb_bridge'

buap_ancdb_bridge:
  active: true

file_repository:
  recording_context_aliases:
    locus: 'context'
    unit: 'trench/area'
    locus_photo: 'context'
    dayplan: 'trench/area'
    locus_relations: 'context relations'
    collected_material_photo: 'collected material & small finds'
    collected_material: 'collected material & small finds'
    unit_narrative: 'trench/area narrative'
    site_note_photo: 'site note'
    site: 'site map'
    pottery_images: 'pottery'
    tags: 'context tags'
#  representations:
#    master:
#      requested_manipulations: [ "FIX_ROTATION", "DROP_EXIF_DATA", "AUTO_WHITE_BALANCE"]

glossary:
  "locus": ["SU", "SUs"]
#  "unit": ["trench", "trenches"]

kiosk:
  global_constants:
    project_logo_bottom: ' '
    project_logo_main: 'Investigaciones BioArqueologicas en la Selva Alta'
    project_logo_top: ''
    project_name: 'Investigaciones BioArqueologicas en la Selva Alta'
    project_short: USTP

  administrationplugin:
    fake_transfer: True

  playgroundplugin:
    active: true
    is_main_index: false

  pwastresstestplugin:
    active: false

