# *********************************************
# urap kiosk config
# *********************************************
import_configurations:
  - kiosk_default_config.yml
  - kiosk_local_config.yml
  - kiosk_secure.yml

config:
  project_id: 'test'
  filemaker_template: '%sync%\filemaker\pvd_recording_template.fmp12'
  expected_filemaker_template_version: '14.2'
  filemaker_db_filename: test_recording.fmp12
  log_level: 'DEBUG'

file_repository:
  recording_context_aliases:
    locus: 'context'
    unit: 'trench/area'
    locus_photo: 'context'
    dayplan: 'trench/area'
    locus_relations: 'context relations'
    collected_material_photo: 'collected material & small finds'
    collected_material: 'collected material & small finds'
    unit_narrative: 'trench/area narrative'
    site_note_photo: 'site note'
    site: 'site map'
    pottery_images: 'pottery'
    tags: 'context tags'


kiosk:
  global_constants:
    project_name: ''
    project_short: 'URAP'
    project_logo_top: ''
    project_logo_main: 'Uronarti'
    project_logo_bottom: 'Uronarti Regional Archaeological Project'

  playgroundplugin:
    active: true
    is_main_index: false

  pwastresstestplugin:
    active: true



