# The file is ignored by github. This here is just the template for it.

config:
  filemaker_db_usr_name: 'admin'  # 'what user id is the admin for the filemaker database?'
  filemaker_db_usr_pwd: 'admin'  # what password does that user have?
  database_usr_name: ''  # user id for postgres with admin privileges
  database_usr_pwd: ''  # password fpr that user id
kiosk:
  SECRET_KEY: ''  # 'Some random UID'
