# *********************************************
# Default Kiosk Config
# *********************************************
'Flask':
  SOME_OPERATION: 'Something'
  SECRET_KEY: "fd82303c-6852-48c1-8165-9e60d4b25b94"
  EXPLAIN_TEMPLATE_LOADING: False
  THREADED: False
  SEND_FILE_MAX_AGE_DEFAULT: 43200

config:
  no_console: True
  sync: '%base_path%\sync\sync'
  sync_plugin_directory: '%base_path%\sync\sync\sync_plugins'
  dataset_definition: '%base_path%\config\dsd\%project_id%_dsd3.yml'
  custom_sync_modules: '%sync%\custom'
  logfile: '%base_path%\log\kiosk_#a_#d#m#y-#H#M.log'
  log_level: 'INFO'
  werkzeug_log_level: 'WARNING'
  log_to_screen: False
  autoload_plugins:
    - 'filemakerrecording'
    - 'redisgeneralstore'
    - 'simpleqcengine'
    - 'locusrelationshook'
    - 'fileexportworkstation'
    - 'reportingdock'
    - '%base_path%\plugins\pwastresstestplugin\pluginpwastresstestdock'

  master_view: '%base_path%\config\dsd\master_view.yml'
  filemaker_export_dir: '%sync%\filemaker\to_work_station'
  filemaker_import_dir: '%sync%\filemaker\from_work_station'
  filemaker_encoding: "UTF-8"
  expected_filemaker_template_version: '15.3'
  file_handling_definition: '%base_path%\config\file_handling.yml'
  default_resolution: "low"
  default_recording_group: "default"
  fork_ignore_missing_files: True
  static_image_path: '%base_path%\static\assets\images'
  image_manipulation_config: '%base_path%\config\image_manipulation_config.yml'
  general_store_plugin: 'redisgeneralstore'
  general_store_class: 'RedisGeneralStore'
  redis_address: '127.0.0.1'
  redis_port: 6379
  job_garbage_collector_sleeps: 120
  test_mode: False
  use_double_commit: False
  file_repository: '%sync%\file_repository'
  default_kiosk_queries: '%base_path%\config\kiosk_queries'
  database_timeout_sec: 5

file_repository:
  cache: '%file_repository%\cache'
  recording_context_aliases:
    locus_photo: "context"
    dayplan: "trench/area"
    locus_relations: "context relations"
    collected_material_photo: "collected material / small find"
    site_note_photo: "site note"
    site: "site map"
    pottery_images: "pottery"
    coordinate_photo: "coordinate"
    coordinate_categories: "coordinate category"

  representations:
    small:
      label: "small thumbnail"
      inherits: "master"
      dimensions: "128,128"
      format_request: "webp"
    medium:
      label: "medium thumbnail"
      inherits: "master"
      dimensions: "256,256"
      format_request: "default"
    master:
      label: "JPEG with max 4000x2000 pixel"
      format_request: "default"
      dimensions: "4000,2000"
      requested_manipulations: [ "FIX_ROTATION", "DROP_EXIF_DATA"]
    1024x768:
      inherits: "master"
      requested_manipulations: [ "DROP_EXIF_DATA" ]
      format_request: "default"
      dimensions: "1024,768"
    RAW2400x2500:
      requested_manipulations: [ "DROP_EXIF_DATA" ]
      format_request: "NEFTIF"
      dimensions: "2400,2500"
    1024x768JPEG:
      label: "1024x768 screen size file"
      requested_manipulations: [ "DROP_EXIF_DATA", "FIX_ROTATION" ]
      format_request: "default"
      dimensions: "1024,768"

  auto_representations: [ 'medium', 'small' ]
  thumbnails: [ 'small', 'medium' ]
  fullscreen_representation: 'master'

  standard_format_requests:
    default:
      "*": "JPEG"
      "PNG": "!"
      "SVG": "!"
    webp:
      "*": "WEBP"
      "SVG": "!"
    NEFTIF:
      "NEF": "JPEG"
      "TIFF": "JPEG"

fileexportworkstation:
  plugins: [ "fileexportcsvdriver","fileexportexceldriver" ]
  file_export_dsd_view: '%base_path%\config\dsd\file_export_view.yml'
  max_export_repo_mbytes: 500
  FileExportTargetZip:
    export_directory: '%base_path%\export'
    export_filename: 'kiosk.zip'
    compression_method: 'DEFLATED'

reportingdock:
  plugins: [ "reportingpdfdriver","reportingexceldriver", "reportinghtmldriver" ]
  base_path: '%base_path%\reporting'
  output_filename_zip: 'kiosk_report_#a_#d#m#y-#H#M.zip'
  compression_method: 'DEFLATED'

file_handlers:
  plugins: [ "defaultfilehandling", "heicfilehandling", "pdffilehandling", "svgfilehandling",
             "webpfilehandling", "jp2filehandling" ]

file_import:
  file_extensions: ["jpg"]
  recursive: True
  sort_sequence_by: "FILE_CREATION_TIME"
  use_coded_filenames: False  # used for sequence import
  skip_qrcodes_proper: True  # used for sequence import
  use_exif_time: False  # used for sequence import
#  image_manipulation_set: qr_code_sequences  # used for sequence import
  use_uuid: True
  log_import: True
  tags: [ ]
  add_only_with_excavation_context: True
  folder_encodings: [ ]
  filename_encodings: [ ]
  max_file_uploads: 10
  load_plugins:
    - "fileimportstandardfilters"
    - "fileimportqrcodefilter"
    - "fileimportexiffilter"

  file_import_filters:
    local_import:
      FileImportStandardValuesFilter:
        active: False
        priority: 0
      FileImportStandardFolderFilter:
        priority: 10
        active: True
        get_context_from_folder: True
        get_date_from_folder: False
      FileImportStandardFileFilter:
        active: True
        get_context_from_file: True
        get_date_from_file: True
        priority: 20
      FileImportQRCodeFilter:
        active: True
        get_excavation_context: True
        get_date: True
        priority: 30
        recognition_strategy: qr_code_sahara
        image_manipulation_sets:
          - qr_code_sahara
          - qr_code_black_velvet
          - qr_code_italy
          - qr_code_peru
      FileImportExifFilter:
        active: False
        get_context_from_exif: False
        get_date_from_exif: True
        get_description_from_exif: False
        priority: 25
    upload:
      FileImportStandardValuesFilter:
        active: False
        priority: 0
      FileImportStandardFileFilter:
        active: False
        get_context_from_file: True
        get_date_from_file: False
        priority: 20
      FileImportQRCodeFilter:
        active: True
        get_excavation_context: True
        get_date: True
        priority: 30
        recognition_strategy: qr_code_sahara
        image_manipulation_sets:
          - qr_code_sahara
          - qr_code_black_velvet
          - qr_code_italy
          - qr_code_peru
      FileImportExifFilter:
        active: False
        get_context_from_exif: False
        get_date_from_exif: True
        get_description_from_exif: False
        priority: 15
    filesequence_import:
      FileImportStandardValuesFilter:
        active: False
        priority: 0
      FileImportStandardFolderFilter:
        priority: 10
        active: False
        get_context_from_folder: True
        get_date_from_folder: True
      FileImportStandardFileFilter:
        active: False
        get_context_from_file: True
        get_date_from_file: False
        priority: 20
      FileImportQRCodeFilter:
        active: True
        get_excavation_context: True
        get_date: True
        priority: 30
        recognition_strategy: qr_code_sequences
        image_manipulation_sets:
          - qr_code_black_velvet
          - qr_code_sequences
      FileImportExifFilter:
        active: False
        get_context_from_exif: False
        get_date_from_exif: False
        get_description_from_exif: True
        priority: 25


kiosk:
  security_token_timeout_seconds: 3600
  reset_file: '%base_path%\reset.yml'
  SECRET_KEY: "fd82303c-6852-48c1-8165-9e60d4b25b94"
  template_path: '%base_path%\templates'
  static_image_path: '%base_path%\static\assets\images'
  temporary_upload_path: '%file_repository%\temp'
  plugin_path: '%base_path%\plugins'
  custom_kiosk_modules: '%base_path%\custom'
  temp_file_max_age_days: 30
  startup_threads: [ ]
  terminal_accent_color_ansi: '[30;41;1m'
  backup_reminder_days: 1
  limit_import_to_paths: True

  login_plugin:
    active: true

  filerepositoryplugin:
    active: true
    is_main_index: false
    menu:
      "file repository": [ "-filerepositoryplugin" ]

    file_icons:
      general: 'dummyfile.svg'
      nef: 'raw.svg'
      pdf: 'pdf.svg'
      svg: 'svg.svg'
      mov: 'mov.svg'

    file_descriptions:
      set1:
        name: "full description"
        primary: [ [ "pottery_images", "collected_material_photo", "locus_photo" ], [ "locus_photo" ], [ "dayplan" ], [ "locus_relations" ], [ "images" ] ]
        secondary: [ [ "images" ] ]
      set2:
        name: "single description"
        primary: [ [ "pottery","collected_material_photo", "locus_photo", "dayplan", "locus_relations" ] ]

  directorsviewplugin:
    active: true
    is_main_index: false
    menu:
      "director's view": [ "-directorsviewplugin" ]

  queryandviewplugin:
    active: true
    is_main_index: false
    menu:
      "query and view data": [ "-queryandviewplugin" ]
    fts:
      language: "english"

  syncmanagerplugin:
    active: true
    is_main_index: true
    default_workstation_type: 'filemaker recording'
    poll_intervall_slow_sec: 10
    poll_intervall_fast_sec: 1
    ports: [ "default", "*", "reporting" ]
    grant_by_wildcard: True
    menu:
      "synchronize": [ "+syncmanagerplugin" ]
      "new dock": [ "+syncmanagerplugin" ]
      "Hub": [ "-syncmanagerplugin" ]
      "sync & dock events": [ "+syncmanagerplugin" ]
    allow_operations: [ ]

  kioskfilemakerworkstationplugin:
    active: true
    no_csrf_defense: true
    menu:
      "prepare filemaker workstations": [ "+syncmanagerplugin" ]
      "import filemaker workstations": [ "+syncmanagerplugin" ]
      "reset all filemaker workstations": [ "+syncmanagerplugin" ]
      "update recording software": [ "+syncmanagerplugin" ]

  fileimportplugin:
    active: true
    is_main_index: false
    allow_operations: [ "local filesystem", "upload", "sequence" ]
    menu:
      "import files": [ "+filerepositoryplugin" ]

  bugsandfeaturesplugin:
    active: true
    is_main_index: false
    menu:
      "import files": [ "-bugsandfeaturesplugin" ]

  administrationplugin:
    active: true
    is_main_index: false
#    backup_filename_template: "backup_#a_#d#m#y-#H#M#S.dmp"
    backup_filename_template: "%project_id%_#a_#d#m#y-#h#m#s.dmp"

    menu:
      "administration": [ "-administrationplugin" ]
      "process management": [ "+administrationplugin" ]
      "backup": [ "+administrationplugin" ]
      "install patch": [ "+administrationplugin" ]
      "privileges": [ "+administrationplugin" ]
      "users": [ "+administrationplugin" ]
      "kiosk queries": [ "+administrationplugin" ]
      "logs": [ "+administrationplugin" ]
      "file picking rules": [ "+administrationplugin", "+syncmanagerplugin" ]
      "quality control rules": [ "+administrationplugin" ]

  playgroundplugin:
    active: false
    is_main_index: false
    menu:
      "developer's playground": [ "-playgroundplugin" ]

  filemanagerplugin:
    active: true
    is_main_index: false
    max_upload_size_mb: 25
    menu:
      "file manager": [ "+administrationplugin" ]
      "topic configuration": [ "+filemanagerplugin" ]

  pointrepositoryplugin:
    active: true
    is_main_index: false
    menu:
      "point repository": [ "-pointrepositoryplugin" ]
    csv:
      columns: ["point_name", "latitude", "longitude", "elevation"]
      skip_lines: 1

  logviewerplugin:
    active: true

  kioskreportingdockplugin:
    active: true

  kioskexportworkstationplugin:
    active: true

  pwastresstestplugin:
    active: false

  locusrelationsapiplugin:
    active: true

  hmlabplugin:
    active: true
    is_main_index: false
    menu:
      "stratigraphy studio": [ "-hmlabplugin" ]
