config:
  format_version: 3
  imports:
    - default_dsd3.yml
    - wc_pottery_dsd3.yml

  contexts:
    forum_record_images:
      type: file_search
      scope:
        anc_forum_record: {}

anc_forum_record:
  meta:
    flags: ["no_filemaker_recording"]
  structure:
    1:
      forum_ssid: [ datatype(VARCHAR), unique(), not_null(), identifier() ]
      forum_filename: [ datatype(VARCHAR) ]
      image_date: [ datatype(VARCHAR) ]
      materials: [ datatype(VARCHAR) ]
      artstor_class: [ datatype(VARCHAR) ]
      work_type: [ datatype(VARCHAR) ]
      repository: [ datatype(VARCHAR) ]
      repository_acc_number: [ datatype(VARCHAR) ]
      location: [ datatype(VARCHAR) ]
      creation_site: [ datatype(VARCHAR) ]
      description: [ datatype(VARCHAR) ]
      photographer: [ datatype(VARCHAR) ]
      id_number: [ datatype(VARCHAR) ]
      type_of_photo: [ datatype(VARCHAR) ]
      image_notes: [ datatype(VARCHAR) ]
      site: [ datatype(VARCHAR) ]
      excavation_photo_type: [ datatype(VARCHAR) ]
      excavation_photo_content: [ datatype(VARCHAR) ]
      feature: [ datatype(VARCHAR) ]
      architecture_mudbrick: [ datatype(VARCHAR) ]
      architecture_stone: [ datatype(VARCHAR) ]
      architectural_conservation_type: [ datatype(VARCHAR) ]
      candid_type: [ datatype(VARCHAR) ]
      object_conservation_location: [ datatype(VARCHAR) ]
      object_notes: [ datatype(VARCHAR) ]
      period: [ datatype(VARCHAR) ]
      data_entered_date: [ datatype(VARCHAR) ]
      data_entered_by: [ datatype(VARCHAR) ]
      season: [ datatype(VARCHAR) ]
      uid_image: [ datatype(UUID), uid_file(), label('photo')]
      uid: [ datatype(UUID), primary()]
      created: [ datatype(TIMESTAMP), replfield_created() ]
      modified: [ datatype(TIMESTAMP), replfield_modified() ]
      modified_by: [ datatype(VARCHAR), replfield_modified_by(), default("''") ]

anc_imported_files:
  meta:
    flags: ["no_filemaker_recording","no_fts"]
  structure:
    1:
      forum_ssid: [ primary(), datatype(VARCHAR), not_null()]
      forum_filename: [ datatype(VARCHAR) ]
      uid_image: [ datatype(UUID)]
      md5_hash: [datatype(VARCHAR), no_sync(), no_file_export()]
      imported_ts: [ datatype(TIMESTAMP)]
