config:
  format_version: 3

repl_deleted_uids:
  meta:
    flags: [ no_file_export ]
  structure:
    1:
      uid: [datatype(UUID), primary(), unique(), default('gen_random_uuid()')]
      deleted_uid: [datatype(UUID), not_null()]
      table: [datatype(VARCHAR)]
      repl_workstation_id: [datatype(VARCHAR)]
      modified: [datatype(TIMESTAMP)]

repl_image_resolution:
  structure:
    3: dropped
    2:
      id: [datatype(SERIAL), primary()]
      workstation_id: [datatype(VARCHAR)]
      recording_context: [datatype(VARCHAR)]
      context: [datatype(VARCHAR)]
      uid_file: [datatype(VARCHAR)]
      file_resolution: [datatype(VARCHAR), not_null()]
    1:
      id: [datatype(SERIAL), primary()]
      workstation_id: [datatype(VARCHAR)]
      table_context: [datatype(VARCHAR)]
      excavation_context: [datatype(VARCHAR)]
      uid_file: [datatype(VARCHAR)]
      file_resolution: [datatype(VARCHAR), not_null()]
  migration:
    3:
      upgrade:
        - drop(*)
    2:
      upgrade:
        - rename("table_context","recording_context")
        - rename("excavation_context","context")

repl_file_picking_rules:
  meta:
    flags: [no_file_export]
  structure:
    1:
      workstation_type: [datatype(varchar), not_null()]
      recording_group: [datatype(varchar), not_null(), default("'default'")]
      order: [datatype(number), not_null()]
      rule_type: [datatype(varchar), not_null()]
      operator: [datatype(varchar)]
      value: [datatype(varchar)]
      resolution: [datatype(varchar), not_null()]
      disable_changes: [datatype(boolean), default(false)]
      misc: [datatype(varchar)]
      uid: [datatype(UUID), uuid_key()] # not using replfield_xxx types to avoid synchronization
      created: [datatype(TIMESTAMP), not_null(), default("now()")]
      modified: [datatype(TIMESTAMP), not_null(),default("now()")]
      modified_by: [datatype(VARCHAR), default("Null")]


repl_workstation:
  structure:
    5:
      id: ["datatype(VARCHAR, 20)", primary()]
      workstation_type: [datatype(VARCHAR)]
      description: [datatype(VARCHAR)]
      state: [datatype(SMALLINT), default(0), not_null()]
      uid: [datatype(UUID), default('gen_random_uuid()'), not_null()]
      fork_time: [datatype(TIMESTAMP)]
      fork_sync_time: [datatype(TIMESTAMP)]
      dsd_version: [datatype(VARCHAR)]
      recording_group: [datatype(VARCHAR)]
      gmt_time_zone: [datatype(VARCHAR)]
      grant_access_to: [datatype(VARCHAR), default("'*'")]
    4:
      id: ["datatype(VARCHAR, 20)", primary()]
      workstation_type: [datatype(VARCHAR)]
      description: [datatype(VARCHAR)]
      state: [datatype(SMALLINT), default(0), not_null()]
      uid: [datatype(UUID), default('gen_random_uuid()'), not_null()]
      fork_time: [datatype(TIMESTAMP)]
      fork_sync_time: [datatype(TIMESTAMP)]
      dsd_version: [datatype(VARCHAR)]
      recording_group: [datatype(VARCHAR)]
      gmt_time_zone: [datatype(VARCHAR)]
    3:
      id: ["datatype(VARCHAR, 20)", primary()]
      workstation_type: [datatype(VARCHAR)]
      description: [datatype(VARCHAR)]
      state: [datatype(SMALLINT), default(0), not_null()]
      uid: [datatype(UUID), default('gen_random_uuid()'), not_null()]
      fork_time: [datatype(TIMESTAMP)]
      fork_sync_time: [datatype(TIMESTAMP)]
      dsd_version: [datatype(VARCHAR)]
      recording_group: [datatype(VARCHAR)]
    2:
      id: ["datatype(VARCHAR, 20)", primary()]
      description: [datatype(VARCHAR)]
      state: [datatype(SMALLINT), default(0), not_null()]
      uid: [datatype(UUID), default('gen_random_uuid()'), not_null()]
      fork_time: [datatype(TIMESTAMP)]
      fork_sync_time: [datatype(TIMESTAMP)]
      dsd_version: [datatype(VARCHAR)]
      recording_group: [datatype(VARCHAR)]
    1:
      id: ["datatype(VARCHAR, 20)", primary()]
      description: [datatype(VARCHAR)]
      state: [datatype(SMALLINT), default(0), not_null()]
      uid: [datatype(UUID), default('gen_random_uuid()'), not_null()]
      fork_time: [datatype(TIMESTAMP)]
      fork_sync_time: [datatype(TIMESTAMP)]
      dsd_version: [datatype(VARCHAR)]
      file_handling: [datatype(VARCHAR)]
  migration:
    5:
      upgrade:
        - add("grant_access_to")
    4:
      upgrade:
        - add("gmt_time_zone")
    3:
      upgrade:
        - add("workstation_type")
    2:
      upgrade:
        - drop("file_handling")
        - add("recording_group")

repl_events:
  structure:
    1:
      uid: [datatype(VARCHAR), uuid_key()]
      ts: [datatype(TIMESTAMP), default("now()"), not_null()]
      event: [datatype(VARCHAR)]
      message: [datatype(VARCHAR)]
      dock: [datatype(VARCHAR), not_null()]
      level: [datatype(NUMBER), default(0)]
      user: [datatype(VARCHAR)]

#repl_workstation_events:
#  structure:
#    2: dropped
#    1:
#      uid: [datatype(VARCHAR), uuid_key()]
#      ts: [datatype(TIMESTAMP), default("now()"), not_null()]
#      event: [datatype(VARCHAR)]
#      message: [datatype(VARCHAR)]
#      workstation: [datatype(VARCHAR), not_null()]
#  migration:
#    2:
#      upgrade:
#        - drop(*)
#
repl_workstation_filemaker:
  structure:
    3:
      x_state_info: [datatype(JSON)]
      id: [datatype(VARCHAR), primary()]
    2:
      id: [datatype(VARCHAR), primary()]
    1:
      id: [datatype(VARCHAR), primary()]
      export_group: [datatype(VARCHAR)]
  migration:
    3:
      upgrade:
        - add("x_state_info")
    2:
      upgrade:
        - drop("export_group")

repl_workstation_file_export:
  structure:
    1:
      id: [datatype(VARCHAR), primary()]
      export_file_format: [datatype(VARCHAR)]
      include_files: [datatype(BOOLEAN)]
      filename_rendering: [datatype(VARCHAR)]

repl_dock_reporting:
  structure:
    1:
      id: [datatype(VARCHAR), primary()]
      query_definition_filename: [datatype(VARCHAR)]
      mapping_definition_filename: [datatype(VARCHAR)]
      template_file: [datatype(VARCHAR)]
      report_file_type: [datatype(VARCHAR)]
      output_file_prefix: [datatype(VARCHAR)]
      variables: [datatype(JSON)]

qc_rules:
  meta:
    flags: [no_file_export]
  structure:
    2:
      id: [datatype(VARCHAR)]
      type: [datatype(VARCHAR)]
      type_param: [datatype(VARCHAR)]
      trigger: [datatype(VARCHAR)]
      suppress_on: [datatype(VARCHAR)]
      process_only_on: [datatype(VARCHAR)]
      objective: [datatype(VARCHAR)]
      inputs: [datatype(VARCHAR)]
      hosts: [datatype(VARCHAR)]
      flag: [datatype(VARCHAR)]
      enabled: [datatype(NUMBER)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created(),default("now()")]
      modified: [datatype(TIMESTAMP), replfield_modified(),default("now()")]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default(null)]
    1:
      id: [datatype(VARCHAR)]
      type: [datatype(VARCHAR)]
      type_param: [datatype(VARCHAR)]
      trigger: [datatype(VARCHAR)]
      suppress_on: [datatype(VARCHAR)]
      process_only_on: [datatype(VARCHAR)]
      objective: [datatype(VARCHAR)]
      inputs: [datatype(VARCHAR)]
      hosts: [datatype(VARCHAR)]
      flag: [datatype(VARCHAR)]
      enabled: [datatype(NUMBER)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by()]
  migration:
    2:
      upgrade:
        - alter("created")
        - alter("modified")
        - alter("modified_by")

qc_flags:
  meta:
    flags: [no_file_export]
  structure:
    2:
      id: [datatype(VARCHAR)]
      severity: [datatype(VARCHAR)]
      message: [datatype(VARCHAR)]
      params: [datatype(VARCHAR)]
      fields_involved: [datatype(VARCHAR)]
      i18n_id: [datatype(VARCHAR)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created(),default("now()")]
      modified: [datatype(TIMESTAMP), replfield_modified(),default("now()")]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default(null)]
    1:
      id: [datatype(VARCHAR)]
      severity: [datatype(VARCHAR)]
      message: [datatype(VARCHAR)]
      params: [datatype(VARCHAR)]
      fields_involved: [datatype(VARCHAR)]
      i18n_id: [datatype(VARCHAR)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by()]
  migration:
    2:
      upgrade:
        - alter("created")
        - alter("modified")
        - alter("modified_by")

qc_message_cache:
  structure:
    1:
      flag_id_data_context: [datatype(VARCHAR), primary(), not_null(), unique()]
      flag_id: [datatype(VARCHAR), not_null()]
      data_context: [datatype(VARCHAR), not_null()]
      severity: [datatype(VARCHAR), not_null()]
      message: [datatype(VARCHAR)]
      fields_involved: [datatype(VARCHAR)]
