config:
  format_version: 3

tables:
  - include_tables_with_instruction("replfield_uuid")
  - include_tables_with_flag("file_export")
  - exclude_tables_with_flag("no_file_export")
  - exclude_fields_with_instruction("local_id")
  - exclude_fields_with_instruction("id_domain")
  - exclude_fields_with_instruction("no_file_export")

