config:
  format_version: 3
  contexts:
      cm_images:
        type: file_search
        scope:
          collected_material:
            collected_material_photo: {}
            su_ceramics:
              pottery_images: {}
      su_ceramics_images:
        type: file_search
        scope:
          su_ceramics:
            pottery_images: {}
su_ceramics:
  structure:
    1:
      id: [datatype(NUMBER),local_id("arch_context")]
      object: [datatype(VARCHAR)]
      func_cat: [datatype(VARCHAR), label("functional category")]
      func_sub_cat: [datatype(VARCHAR), label("functional sub category")]
      form_and_comparisons: [datatype(VARCHAR)]
      measurements: [datatype(VARCHAR)]
      drawn: [datatype(VARCHAR)]
      photographed: [datatype(VARCHAR)]
      coarseness: [datatype(VARCHAR)]
      fabric: [datatype(VARCHAR)]
      manufacture: [datatype(VARCHAR)]
      finish_and_decoration: [datatype(VARCHAR)]
      other_observations: [datatype(VARCHAR)]
      chronology: [datatype(VARCHAR)]
      cm_uid: [datatype(UUID), join("collected_material")]
      arch_domain: [datatype(VARCHAR), id_domain("arch_context")]
      arch_context: [datatype(VARCHAR), identifier(),label("#:#(/$/glossary/fragment)")]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default(null)]

su_ceramics_preprocessing_entry:
  structure:
    2:
      cm_uid: [datatype(UUID), join("collected_material")]
      category_1: [datatype(VARCHAR)]
      category_2: [datatype(VARCHAR)]
      count: [datatype(NUMBER),default(0)]
      weight: [datatype(NUMBER),default(0)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default(null)]
    1:
      cm_uid: [datatype(UUID), join("collected_material")]
      category_1: [datatype(VARCHAR)]
      category_2: [datatype(VARCHAR)]
      count: [datatype(NUMBER)]
      weight: [datatype(NUMBER)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default(null)]
  migration:
    2:
      upgrade:
        - alter("count")
        - alter("weight")


pottery_images:
  structure:
    2:
      uid_pottery: [datatype(UUID), join("su_ceramics")]
      description: [datatype(VARCHAR), describes_file(uid_image)]
      uid_image: [datatype(UUID), uid_file(), file_location_for("su_ceramics")]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default(null)]
    1:
      uid_pottery: [datatype(UUID), join("su_ceramics")]
      description: [datatype(VARCHAR), describes_file(uid_image)]
      uid_image: [datatype(UUID), uid_file(), file_location_for("su_ceramics")]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default('Null')]
  migration:
    2:
      upgrade:
        - alter("modified_by")
