# message severity
MSG_SEVERITY_HIGHEST = 10
MSG_SEVERITY_CRITICAL = 10
MSG_SEVERITY_ERROR = 5
MSG_SEVERITY_WARNING = 2
MSG_SEVERITY_INFO = 0
MSG_SEVERITY_DEBUG_ERROR = -2
MSG_SEVERITY_DEBUG_WARNING = -5
MSG_SEVERITY_DEBUG_INFO = -10
MSG_SEVERITY_LOWEST = -10

# message classes
SYS_MSG_CLASS_ERROR = "UNCLASSIFIED ERROR"
SYS_MSG_CLASS_STARTUP_ERROR = "STARTUP ERROR"
SYS_MSG_CLASS_MAINTENANCE = "MAINTENANCE MESSAGE"
SYS_MSG_CLASS_TESTING = "TESTING CLASS FOR TESTS"

# message ids
# make sure that the string representation can serve as an id in html!

SYS_MSG_ID_STORE_NOT_READY = "SYS_MSG_ID_STORE_NOT_READY"
SYS_MSG_ID_TEMP_DIR_MISSING = "SYS_MSG_ID_TEMP_DIR_MISSING"
SYS_MSG_ID_MCP_NOT_UP = "SYS_MSG_ID_MCP_NOT_UP"
SYS_MSG_ID_CHECKUP_EXCEPTION = "SYS_MSG_ID_CHECKUP_EXCEPTION"
SYS_MSG_ID_MESSAGING_CORRUPT = "SYS_MSG_ID_MESSAGING_CORRUPT"
SYS_MSG_ID_ADMIN_CREATED = "SYS_MSG_ID_ADMIN_CREATED"
SYS_MSG_ID_ADMIN_GROUP_CREATED = "SYS_MSG_ID_ADMIN_GROUP_CREATED"
SYS_MSG_ID_TEST_LONER = "SYS_MSG_ID_TEST_LONER"
SYS_MSG_ID_TEST_MULTI = "SYS_MSG_ID_TEST_MULTI"
SYS_MSG_ID_MIGRATION_FAILED = "SYS_MSG_ID_MIGRATION_FAILED"
SYS_MSG_ID_REBUILD_FIC_FAILED = "SYS_MSG_ID_REBUILD_FIC_FAILED"
SYS_MSG_ID_SYSTEM_RESTORED = "SYS_MSG_ID_SYSTEM_RESTORED"
SYS_MSG_ID_DEVELOPMENT_ENVIRONMENT_ACTIVE = "SYS_MSG_ID_DEV_ENV"
SYS_MSG_ID_DEVELOPMENT_GENERATE_SYSTEM_MESSAGE = "SYS_MSG_ID_DEVELOPMENT_GENERATE_SYSTEM_MESSAGE"
SYS_MSG_ID_BACKUP_REMINDER = "SYS_MSG_ID_BACKUP_REMINDER"
SYS_MSG_ID_BEFORE_RESTORE_FAILED = "SYS_MSG_ID_BEFORE_RESTORE_FAILED"
SYS_MSG_ID_PATCH_SUCCESSFUL = "SYS_MSG_ID_PATCH_SUCCESSFUL"
SYS_MSG_ID_PATCH_FAILED = "SYS_MSG_ID_PATCH_FAILED"

# message id option
# The default case is that this msg id can actively only exist ONCE in the whole
# message system. It replaces the uid in this case.
SYS_MSG_LONER = False

# this msg id can occur several times among the active messages.
SYS_MSG_MULTI = True

# id to class map
SYS_MSG_ID_DETAILS = {
    SYS_MSG_ID_TEST_LONER: (SYS_MSG_CLASS_TESTING, MSG_SEVERITY_ERROR, SYS_MSG_LONER),
    SYS_MSG_ID_TEST_MULTI: (SYS_MSG_CLASS_TESTING, MSG_SEVERITY_ERROR, SYS_MSG_MULTI),
    SYS_MSG_ID_STORE_NOT_READY: (SYS_MSG_CLASS_STARTUP_ERROR, MSG_SEVERITY_ERROR, SYS_MSG_LONER),
    SYS_MSG_ID_MCP_NOT_UP: (SYS_MSG_CLASS_STARTUP_ERROR, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_CHECKUP_EXCEPTION: (SYS_MSG_CLASS_STARTUP_ERROR, MSG_SEVERITY_ERROR, SYS_MSG_LONER),
    SYS_MSG_ID_MESSAGING_CORRUPT: (SYS_MSG_CLASS_ERROR, MSG_SEVERITY_ERROR, SYS_MSG_LONER),
    SYS_MSG_ID_ADMIN_CREATED: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_ADMIN_GROUP_CREATED: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_MIGRATION_FAILED: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_ERROR, SYS_MSG_LONER),
    SYS_MSG_ID_REBUILD_FIC_FAILED: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_TEMP_DIR_MISSING: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_SYSTEM_RESTORED: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_DEVELOPMENT_ENVIRONMENT_ACTIVE: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_BACKUP_REMINDER: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_BEFORE_RESTORE_FAILED: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_DEVELOPMENT_GENERATE_SYSTEM_MESSAGE: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_WARNING, SYS_MSG_LONER),
    SYS_MSG_ID_PATCH_SUCCESSFUL: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_INFO, SYS_MSG_LONER),
    SYS_MSG_ID_PATCH_FAILED: (SYS_MSG_CLASS_MAINTENANCE, MSG_SEVERITY_ERROR, SYS_MSG_LONER),
}

